name       : python-rsa
version    : 4.8.0
release    : 6
source     :
    - https://pypi.io/packages/source/r/rsa/rsa-4.8.tar.gz : 5c6bd9dc7a543b7fe4304a631f8a8a3b674e2bbfc49c2ae96200cdbe55df6b17
license    : Apache-2.0
component  : programming.python
summary    : A pure-Python RSA implementation
description: |
    Python-RSA is a pure-Python RSA implementation. It supports encryption and decryption, signing and verifying signatures, and key generation according to PKCS#1 version 1.5. It can be used as a Python library as well as on the commandline.
builddeps  :
    - python-asn1
    - python-mock
    - python-mypy
rundeps    :
    - python-asn1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
