name       : python-rsa
version    : 4.7.1
release    : 4
source     :
    - https://pypi.io/packages/source/r/rsa/rsa-4.7.1.tar.gz : 9d74d1ff850745c9802cd6b53382bfeec7f6dbe4e26ee2759241ed1e7b0ecf5d
license    : Apache-2.0
component  : programming.python
summary    : A pure-Python RSA implementation
description: |
    Python-RSA is a pure-Python RSA implementation. It supports encryption and decryption, signing and verifying signatures, and key generation according to PKCS#1 version 1.5. It can be used as a Python library as well as on the commandline.
builddeps  :
    - python-asn1
    - python-mock
    - python-mypy
rundeps    :
    - python-asn1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
