name       : python-rsa
version    : 4.7.2
release    : 5
source     :
    - https://pypi.io/packages/source/r/rsa/rsa-4.7.2.tar.gz : 9d689e6ca1b3038bc82bf8d23e944b6b6037bc02301a574935b2dd946e0353b9
license    : Apache-2.0
component  : programming.python
summary    : A pure-Python RSA implementation
description: |
    Python-RSA is a pure-Python RSA implementation. It supports encryption and decryption, signing and verifying signatures, and key generation according to PKCS#1 version 1.5. It can be used as a Python library as well as on the commandline.
builddeps  :
    - python-asn1
    - python-mock
    - python-mypy
rundeps    :
    - python-asn1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
