name       : python-rsa
version    : 4.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/cb/d0/8f99b91432a60ca4b1cd478fd0bdf28c1901c58e3a9f14f4ba3dba86b57f/rsa-4.0.tar.gz : 1a836406405730121ae9823e19c6e806c62bbad73f890574fff50efa4122c487
license    : Apache-2.0
component  : programming.python
summary    : A pure-Python RSA implementation
description: |
    Python-RSA is a pure-Python RSA implementation. It supports encryption and decryption, signing and verifying signatures, and key generation according to PKCS#1 version 1.5. It can be used as a Python library as well as on the commandline.
builddeps  :
    - python-asn1
    - python-mock
rundeps    :
    - python-asn1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
